### ISSUE TITLE
Probleme grave avec les niveaux

### ISSUE THREAD

**Issue by rcherp89** [MDDP/ProjetInfo#1]
La partie graphique est quasiment terminée mais la je suis tombé sur un problème massif: le fichier test.txt lance le niveau avec le bouton "reprendre la partie", mais le niveau niveau1.txt avec EXACTEMENT le même contenu que test.txt (j'ai copié collé) ne marche pas. J'ai besoin que ça marche pour finir la partie graphique, alors bougez vous il reste plus beaucoup de temps avant le rendu. Ah et les fonctions de résolution et d'aide ont été ajoutés au graphique mais elles font rien. Voila dites moi si je dois faire un truc en plus.

**Comment by rotsix** [comment]
ok j'ai trouvé le problème,
ça vient de la différence d'encodage entre le fichier test que j'ai écrit via un encodage UNIX, alors que les autres fichiers ont été écrit via un encodage windaube.

La différence vient du type de fin de ligne (\n pour unix, \r\n pour windows).
J'ai ré-écrit tous les fichiers à la main (oui..) pour que ça marche.

Issue partiellement close !

**Comment by rcherp89** [comment]
Bien joué la découverte, j'aurais pas trouvé seul. Je vais retenter du coup !
